openapi: 3.0.1
info:
  title: YouTube Search and Summarize
  description: A plugin that allows chatGPT to search YouTube video content if given a youtube url.
  version: 'v1'
servers:
  - url: PLUGIN_HOSTNAME
paths:
  /search/youtube/transcript:
    post:
      operationId: getTranscript
      summary: Get the transcript of a youtube video for summarization.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
              required:
                - url
      responses:
        "200":
          description: OK
          content:
            application/json:
              scehma:
                $ref: '#/components/schemas/getTranscriptResponse'
  /search/youtube/query:
    post:
      operationId: searchVideos
      summary: Search for a list of videos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                iso_3166-1_alpha-2_code:
                  type: string
                iso_639-1_code:
                  type: string
              required:
                - query
      responses:
        "200":
          description: OK
          content:
            application/json:
              scehma:
                $ref: '#/components/schemas/getSearchVideosResponse'
  /search/youtube/next:
      post:
        operationId: nextPageOfVideos
        summary: Get the next page of results using the query_id of the previous search.
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  query_id:
                    type: string
                required:
                  - query_id
        responses:
          "200":
            description: OK
            content:
              application/json:
                scehma:
                  $ref: '#/components/schemas/getNextPageResponse'

components:
  schemas:
    getTranscriptResponse:
      type: object
      properties:
        transcript:
          type: string
          description: The transcript of the youtube video.
    getSearchVideosResponse:
      type: object
      properties:
        videos:
          type: string
          description: A list of videos in json format.
        query_id:
          type: string
          description: The query id of the search that the user can use to get the next page of results.
    getNextPageResponse:
      type: object
      properties:
        videos:
          type: string
          description: A list of videos in json format.
        query_id:
          type: string
          description: The query id of the search that the user can use to get the next page of results.